glass/observations.py

Added Smail PDF to observations.
I am not sure about the median value normalisation (not sure if the value quoted in Refregier & Amara) is something general or not...
Deliberately did not add an option to re-normalise the pdf to a certain value.

ENH: Smail et al. (1994) source redshift distribution

---

glass/observations.py

Add the missing functions in the `glass.observations` module to the docs.

DOC: missing functions in observations module

---

glass/galaxies.py
glass/test/test_galaxies.py

This PR adds the intrinsic normal distribution for galaxy ellipticity. It is described in the upcoming GLASS paper.

ENH: intrinsic normal galaxy ellipticity distribution

---

glass/galaxies.py
glass/util.py

This PR closes #28 by refactoring the galaxies module into logical units. It also add documentation to everything in a better format.

ENH: split galaxy generators into logical units

---

glass/fields.py

Change the name of some `cls` variables to `gls` when they are in fact Gaussian Cls.

MAINT: use `gls` instead of `cls` for Gaussian Cls

---

README.md
docs/user/definitions.rst
docs/user/extensions.rst
docs/user/getting_started.rst
glass/galaxies.py
glass/shapes.py

Some slight improvements to the user documentation.

DOC: improve user documentation

---

CITATION.md
README.md

Adds some useful badges to the README file. Paper links need to be updated when available.

DOC: add CITATION and some badges to README

---

CHANGELOG.md
docs/manual/releases.rst
setup.cfg

Release commit for GLASS 2023.2.

REL: glass 2023.2

---

setup.cfg

Commit to begin development on glass 2023.3.

REL: begin glass 2023.3 development

---

.github/workflows/pull_request.yml
.github/workflows/pull_request_review.yml
CONTRIBUTING.md
commitlint.rules.js

Add a description of the git workflow to the contributor guidelines.
Also set up actions to enforce the workflow:
* An action that checks the pull request title formatting.
* An action that automatically tracks approving reviews in the text.
Fixes: #78
Reviewed-by: @arthurmloureiro

DEV: implement workflow for issues and pull requests

---

.commitlint.rules.js
.github/workflows/pull_request.yml

Tweak the settings for commitlint such that any case in the subject line is allowed.  Also rename the rules file to make it less prominent.

DEV: tweak commitlint config

---

README.md
docs/manual/installation.rst

Add information about the mailing list for announcements of new GLASS releases.
Fixes: #66

DOC: add announcement mailing list information

---

CHANGELOG.md
docs/manual/releases.rst
setup.cfg

REL: glass 2023.5

---

glass/points.py
glass/test/test_points.py

Changes the point sampling functions `positions_from_delta()` and `uniform_positions()` to return an iterator over batches of samples.
Closes: #98
Changed: The point sampling functions `positions_from_delta()` and `uniform_positions()` now return an iterator

API(points): iterative sampling of positions

---

.readthedocs.yml
glass/core/algorithm.py
glass/core/test/test_algorithm.py
glass/shells.py
glass/test/test_shells.py
pyproject.toml

Adds the `"nnls"` method to the `partition()` function, which returns a non-linear least-squares solution. This should be used when each shell's contribution is required to be positive, e.g. when partitioning densities.
Closes: #140
Added: The glass.core.algorithm module.
Added: The new partition(method="nnls") function computes a partition with non-negative contributions for each shell.
Changed: The default method for partition() is now "nnls".

ENH(shells): non-negative least squares partition

---

.github/workflows/pull_request_review.yml

This should fix the PR review action.

DEV: add write permission to PR review action

---

.github/workflows/test.yml

Adds Python 3.12 to testing suite.
Closes: #133

DEV: add Python 3.12 to testing suite

---

CHANGELOG.md
docs/manual/releases.rst

REL: glass 2024.1

---

pyproject.toml

XRef #187 
Reviewed-by: Patrick J. Roddy <patrickjamesroddy@gmail.com>
Reviewed-by: Nicolas Tessore

gh-187: add scientific python recommended pytest config

---

.git-blame-ignore-revs
.github/pr-title-checker-config.json
.github/workflows/test.yml
.pre-commit-config.yaml
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Closes #226. https://prettier.io is a formatter for a variety of files. Helps for consistency etc. Will add to the `git blame` file, like in #199, afterwards.

gh-226: run `prettier` over the repo via a `pre-commit` hook

---

.github/workflows/examples.yml
.github/workflows/test.yml

Draft PRs no longer trigger the test actions.
Closes: #233

gh-233: don't run workflows on draft PRs

---

README.md

gh-180: add badges for pre-commit, python versions, discussion, license

---

.gitignore
tests/test_fits.py

gh-238: utilise tmp_path correctly in tests

---

tests/test_points.py

Add tests and bump coverage to ~97 for `glass.points`.
Closes: #272

gh-272: add tests for glass.points

---

glass/ext/__init__.py
glass/fields.py
glass/shells.py
tests/test_points.py

Some imports weren't at the top. Also spotted a double `TYPE_CHECKING` block.

gh-419: fix imports

---

.github/workflows/release.yml

Fix linting

---

glass/shells.py

Closes #456. Discovered in #449. The contents of the two functions are near identical so makes sense to combine.

gh-456: call `redshift_grid` within `distance_grid`

---

README.md
docs/manual/installation.rst

Add instructions to install glass from conda-forge.
Closes: #470

gh-470: instructions to install using conda

---

glass/core/array.py
glass/points.py
glass/shells.py

CI was broken. Linting was fixed but broke tests. Merging this in to neaten up #471.

Manual revert of #467

---

.github/workflows/test.yml

Fix the root path for coveralls. Working -
Closes: #515

gh-515: fix coveralls

---

glass/core/array.py
pyproject.toml

Missed from the merging in #507. Not sure why `ruff` wasn't smart enough to pick this one up. Glad to get rid of the extra dependency though.

gh-501: changes missed in #507

---

glass/grf/_core.py
glass/shells.py

Moves custom types into `TYPE_CHECKING` block as suggested in https://github.com/glass-dev/glass/pull/507#discussion_r1956180229.

gh-501: move custom types into `TYPE_CHECKING`

---

.readthedocs.yml
pyproject.toml

Fixes temporary issue with Sphinx 8.2.0. Also should fix the version in latest to not be shown.
Closes: #525

gh-525: fix docs

---

.pre-commit-config.yaml

These are too frequent IMO and becoming a distraction. Monthly is a good balance between staying up-to-date without being too noisu.

Change the pre-commit updates to be monthly

---

CHANGELOG.md
docs/manual/releases.rst

Creates the appropriate changes in the CHANGELOG and release notes that can then be used in the release. Not further changes to be made before this PR goes in.
Closes: #532

gh-532: prepare for the `v2025.1` release

---

CONTRIBUTING.md

Add documentation on how to effectively use the all-contributors bot and CLI.
Closes: #552
Closes: #553

gh-552: add docs on all-contributors

---

.github/workflows/test.yml
tests/test_fields.py

Updates the tests to use absolute tolerance (`1e-5`).
Closes: #583

gh-583: fix flakiness of `test_generate`

---

examples/2-advanced/legacy-mode.ipynb

Remove redunant `glass.ext.camb` import from the legacy notebook
Fixes: #585

gh-585: remove redunant `glass.ext.camb` import
