glass/random.py
This PR add extrapolates cls to the bandlimit with an exponential decay. This smoothes the transforms when the lmax of the input is below the bandlimit. For lmax below ~2nside or so, the lognormal realisations should realise the input cls more or less exactly.
This PR also fixes the pixel window function.
=> ENH: extrapolate cls to smooth transforms

glass/sim.py
This PR changes the shell definition `zspace` and `xspace` such that when `dz` or `dx` are specified, the resulting shells **cover** the given redshift range.  Before, they would work like numpy's `arange` in that the shells are **included** in the given redshift range.
For example, when using `xspace(c, 0., 2., dx=200)` the last shell has an upper redshift of 2.013991, thus covering the entire 0 to 2 range.
Tagging reviewers so that they can let me know if this is a problem in their applications.
=> ENH: shells cover full redshift range

glass/galaxies.py, glass/random.py, glass/util.py
Closes #26 by removing the pixel window function from the random generation of the matter fields.  This fixes the spurious integration in the weak lensing fields.  Instead, the galaxy density is integrated after the galaxy bias has been applied to the matter field.
=> ENH: do not integrate matter fields

glass/fields.py
This should prevent mix-ups between the `shift` and `ncorr` parameters.
=> API: ncorr is keyword parameter for random fields

glass/fields.py, glass/user.py
Adds two functions `save_cls` and `load_cls` to `glass.user` that can save and load the GLASS cls format as numpy arrays.  They do so by concatenating all cls into a single array of values, and keeping track of the necessary splits to return the concatenated array to the original list. Both are stored in a npz file.
Also changes some functions to use an empty list instead of `None` for missing Cls.
=> ENH: User functions to save and load Cls

CHANGELOG.md, docs/user/index.rst, docs/user/releases.rst
To keep track of the changes between GLASS releases, this PR adds a [changelog](https://keepachangelog.com) to the repository, and a "release notes" page to the documentation.
=> DOC: Changelog and release notes

README.md, docs/user/getting_started.rst
Remove links to Gitter due to its recent migration to a service that isn't as easy to use as before.
We can add an alternative at some point in the future, if one emerges.
=> DOC: remove Gitter links

CONTRIBUTING.md
This commit adds a few of the contributing guidelines that exist at this point, which are: commit prefixes, version increases, and the release procedure.
These may not be very useful to new contributors, but at least we have them in some accessible place for now.
=> INF: first past at contributing guidelines

glass/points.py, glass/test/test_points.py, setup.cfg
Allow dimensional input to the sampling functions in `glass.points`. In the language of the `glass.galaxies` module, leading dimensions would correspond to separate galaxy populations.
Numpy broadcasting rules are applied to the leading dimensions.
Since the sampling returns a potentially different number of points for each extra dimension, the return value for dimensional input is a 1-D list of points, corresponding to the flattened leading dimensions.
To simplify working with dimensional output, the sampling functions now always return a third value `counts` along with longitudes and latitudes, which is either an int or a list of ints.  Because the return values are different, this is a breaking change.
BREAKING CHANGE: Position sampling returns counts alongside points.
Fixes: #77
=> API(points): support for array inputs

glass/math.py, glass/points.py, glass/test/test_math.py, glass/test/test_points.py
Amend the changes #80 to return only flat, 1-D columns of longitudes and latitudes from the `glass.points` sampling functions, even for inputs with extra dimensions. This makes it easier to pass the results to other functions, which might not accept ragged lists of arrays.
If extra dimensions are present in the inputs, the output `count` is an array of counts with the shape of the extra dimensions. This is convenient, because it can be passed directly e.g. as the `size=` argument in random sampling functions.
A `count` array also makes it easy to create a column of labels for the sampled populations of points:
label_col = np.repeat(labels, count.flat)
The change also introduces a `broadcast_leading_axes()` utility function that broadcasts a varying number leading axes for given arrays. …
=> API(points): return flat lists of points

glass/galaxies.py, glass/math.py, glass/test/test_galaxies.py
This change brings the inputs of the `glass.galaxies` module in line with the outputs of the `glass.points` sampling functions after changes #80 and #86.
The `redshifts_from_nz()` function now supports arrays for the `count` parameter (e.g. as returned by the `glass.points` functions) as well as multi-dimensional distributions. If multiple populations are being sampled, the resulting output from each population (i.e. extra input dimension) is concatenated and returned as a flat 1-D column.
The old `gal_pop` return value no longer exists; the population information is already decided by the points sampling and encoded in the `count` array.  As mentioned in #85, it is now easy to generate a column of arbitrary population labels using `np.repeat(labels, count.flat)`.
Also changed is that …
=> API(galaxies): change handling of array inputs and populations

.commitlint.rules.js, glass/core/__init__.py, glass/core/array.py, glass/core/constants.py, glass/core/test/test_array.py, glass/galaxies.py, glass/observations.py, glass/points.py, glass/shells.py, glass/test/test_dummy.py
Moves core functionality that is used by other, user-facing modules into the `glass.core` module.
Currently provides submodules `glass.core.array` and `glass.core.constants`, which contain the respective array functionality and constants from the ex-`glass.math` module.
The `glass.math` module, which was not documented and meant to be internal to other modules, has been removed.
In the future, the `glass.core` module is expected to serve as a namespace for further implementation helpers.
Fixes: #87
=> MNT(core): create module for core functionality

glass/user.py
Remove the profiling tools from the `glass.user` module, as GLASS is not trying to be in the profiling game.
For a replacement that enables easy, automated profiling and logging of all functions calls in a GLASS script, I made the [`easyprofile`](https://github.com/ntessore/easyprofile) package.
Fixes: #76
=> API(user): remove profiling functions

.github/test-constraints.txt, .github/workflows/test.yml
Run the unit tests with all supported Python versions (CPython 3.7 to 3.11).
Fixes: #92
=> DEV: run tests with multiple Python versions

CITATION.md, README.md, docs/user/publications.rst
Updates the citations in the README and the docs to the accepted version of the GLASS paper.
Does not fix the docstrings which refer to the paper.
Fixes: #74
=> DOC: update citation info

glass/shapes.py, glass/test/test_shapes.py
Change the `ellipticity_gaussian()` and `ellipticity_intnorm()` functions in `glass.shapes` to support array inputs for the `count` and `sigma` parameters.  The outputs are a flat list of concatenates samples for each input axis.
Closes: #100
Changes: `ellipticity_gaussian()` and `ellipticity_intnorm()` accept array inputs
=> ENH(shapes): shape sampling accepts array input

glass/__init__.py, glass/all.py, glass/ext/__init__.py
Introduces two related changes:
* Create a `glass.ext` namespace package for extensions.
* Make `glass` no longer a namespace package, by adding an `__init__.py`.
To be able to load namespace packages under non-namespace packages, a pkgutil-type namespace loader is used that looks for extensions having a `glass` module with a `glass.ext` submodule.
This is a breaking change for the `glass.camb` package and the examples, but we want to follow the best practices for plugins, and prevent further breakages of the entire `glass` module further down the line.
No symbols are added to `glass/__init__.py` yet (apart from the version), and everything continues to be imported via the submodules for the time being. Making all imports through the `glass` module itself will require a larger …
=> API: make glass.ext the namespace for extensions

glass/core/array.py, glass/core/test/test_array.py
Fixes the incorrect extrapolation in `glass.core.array.trapz_product()` by making sure the interval over which all functions are interpolated telescopes down to the union of the input intervals.  This caused a bug in `glass.points.effective_bias()`.
Fixes: #104
Fixed: Incorrect extrapolation in `glass.core.array.trapz_product()`, causing a bug in `glass.points.effective_bias()`
=> BUG(core): fix extrapolation in trapz_product()

docs/user/definitions.rst, glass/lensing.py, glass/test/test_lensing.py
Adds functions to simulate deflections due to weak gravitational lensing:
* `from_convergence()` computes other weak lensing fields from the convergence
* `deflect()` applies deflections to a set of positions
An exact definition of what "deflection" means in GLASS is added to the glossary.
This functionality so far only covers the raw physical process of deflecting a point.  To compute the observed positions of a set of sources under weak lensing, we will need a new high-level function `lensed_positions()`, say, that solves the lensing equation by repeatedly calling `deflect()`.
Closes: #106
Added: `deflect()` applies deflections to positions
Added: `from_convergence()` returns other lensing fields given the convergence
Deprecated: `shear_from_convergence()` is deprecated in favour of …
=> ENH(lensing): deflections from weak lensing

CHANGELOG.md, CONTRIBUTING.md, docs/manual/releases.rst
glass 2023.6 (30 Jun 2023)
--------------------------
- There is some support for simulating the deflections due to weak gravitational lensing:
- The `deflect()` function applies deflections to positions.
- The `from_convergence()` function returns one or more other lensing fields given the convergence.
- The `shear_from_convergence()` function is deprecated in favour of `from_convergence()`.
- The `glass` module is no longer a namespace package.  The new `glass.ext` namespace is reserved for extensions instead.  This is done to follow best practices, so that a bad extension can no longer break all of *GLASS* by mistake.  The `glass.all` meta-module is no longer necessary.
- The point sampling functions `positions_from_delta()` and `uniform_positions()` now return an iterator over points. …
=> REL: glass 2023.6

glass/galaxies.py, glass/test/test_galaxies.py
Adds `lower=` and `upper=` keyword parameters to the `gaussian_phz()` function to sample Gaussian photometric redshifts within the given limits.
This currently uses a trivial rejection sampler from the full normal distribution, so it can easily become very inefficient if the bounds don't contain significant probability mass.  Needs to be improved for serious use.
Closes: #114
Changed: The `gaussian_phz()` function now accepts bounds using `lower=` and `upper=` keyword parameters.
=> ENH: specify bounds for Gaussian photometric redshifts

.pre-commit-config.yaml, glass/galaxies.py
Fixes a print statement left in #115.
Also makes sure this doesn't happen again by adding the `flake8-print` plugin to the pre-commit config.
=> BUG: remove stray print statement

docs/user/how-glass-works.rst, glass/shells.py
Adds window functions `linear_windows()` and `cubic_windows()` that correspond to linear and cubic spline interpolation, respectively.
Documentation is updated to give an overview of available window functions.
Closes: #118 
Added: New `linear_windows()` and `cubic_windows()` window functions for shells.
=> ENH(shells): radial windows for linear and cubic interpolation

glass/fields.py, glass/test/test_fields.py
Add a function `getcl()` that takes a list of angular power spectra in GLASS order and returns the entry corresponding to a pair of indices `i` and `j`.
Closes: #112
Added: Function `getcl()` to return angular power spectra by index from a list using GLASS ordering.
=> ENH(fields): return angular power spectrum by index pair

glass/shells.py, glass/test/test_shells.py
Change the `partition()` function to return an array of weights such that the weighted sum of window functions approximates the given input function.  This can be used to directly obtain e.g. the galaxy densities in each shell to match a target distribution $dN/dz$:
```py
ngal = partition(z, dndz, shells)
```
For overlapping window functions, there are in general many ways to combine shells to match a given function. The `partition()` function currently implements least-squares (`method="lstsq"`) and the restriction of the target function to the shell, followed by integration (`method="restrict"`). The latter was previously the default procedure for tophat windows.
Closes: #121
Changed: The `partition()` function now returns an array of weights to approximate the given function by the …
=> API(shells): partition() to fit windows to function

CHANGELOG.md, docs/manual/releases.rst
glass 2023.7 (1 Aug 2023)
-------------------------
* New radial window functions `linear_windows()` and `cubic_windows()`, which correspond to linear and cubic spline interpolation of radial functions, respectively.  These are overlapping window functions, and it has been difficult to obtain accurate matter power spectra so far.
* The `partition()` function now returns an array of weights to approximate a given function by the window functions.  This is necessary to obtain an accurate fit of redshift distributions by overlapping window functions.  For example, to get the array of galaxy densities in each shells from `dndz`, one would now do:
ngal = partition(z, dndz, shells)
* A new function `getcl()` was added to return angular power spectra by index from a list using GLASS ordering.
* …
=> REL: glass 2023.7

glass/galaxies.py, glass/test/test_galaxies.py
Adds a function `redshifts()` that samples redshifts from a distribution which follows the profile of a radial window function.
Closes: #127
Added: Function `redshifts()` to sample redshifts following a radial window function.
=> ENH(galaxies): sample redshifts from radial window

glass/shells.py, glass/test/test_shells.py
Fix the `partition()` function for multi-dimensional arrays.  The axis corresponding to the shells is now the *first* one.
Fixed: partition() now works correctly with functions having extra axes.
Changed: The output of partition() now has the shells axis as its first.
=> BUG(shells): fix partition() for multi-dimensional arrays

glass/core/algorithm.py, glass/shells.py, glass/test/test_shells.py
Most importantly, fixes a bug in `partition_nnls()` which rendered that function useless.
Secondly, optimises `partition_nnls()` by using a QR factorisation of the problem before calling `nnls()` on an equivalent but much smaller problem.
Finally, adds a new integral constraint for both `nnls` and `lstsq` which ensures that the sum of the partition recovers the integral of the input function.
Fixes: #144
Fixed: A bug in `partition()` with the default method.
Changed: Both `partition(method="nnls")` and `partition(method="lstsq")` now have an additional integral constraint so that the sum of the partition recovers the integral of the input function.
=> BUG(shells): fix and improve partition() with NNLS

glass/core/array.py, glass/fields.py, glass/lensing.py, glass/points.py, glass/test/test_lensing.py, glass/test/test_points.py
Adds a function `effective_cls()` which takes a list of weights for each shell and the angular matter power spectrum and returns an array of the effective spectra for when matter shells are combined using the given weights. This can be used to exactly predict what the angular power spectra coming out of a simulation will be after discretisation.
To obtain the angular galaxy power spectrum, a new function `position_weights()` computes the weights corresponding to `positions_from_delta()`. To obtain the angular convergence power spectrum, a new function `multi_plane_weights()` computes the weights corresponding to `MultiPlaneConvergence`.
Closes: #130
Added: A new function `effective_cls()` which combines power spectra using a list of weights, which models what happens in the simulation. …
=> ENH(fields): compute effective spectra of a simulation

glass/shells.py
Adds a function `combine(z, weights, shells)` that computes the linear combination of the window functions in *shells* using coefficients from *weights* evaluated in the redshifts *z*.  This is hence the inverse operation to `partition()`, which returns *weights*.
Closes: #147
Added: A new function `combine()` that evaluates the linear combination
of radial window functions with given weights.
=> ENH(shells): evaluate a linear combination of window functions

glass/fields.py
Fixes a bug in the `effective_cls()` function that caused the returned arrays to be 1 entry too long when `lmax` was not given explicitly.
Closes: #152
Fixed: A bug in `effective_cls()` that caused arrays to be one entry too
long if `lmax` was not given explicitly.
=> BUG(fields): infer correct lmax in effective_cls()

docs/conf.py
Update the URL to the GLASS examples documentation in the intersphinx configuration.
Fixed: Now uses the updated intersphinx URL for the GLASS examples.
Reviewed-by: baugstein
=> DOC: fix intersphinx URL for examples

CITATION.bib
Changes the citation file format to `.bib` and uses BibTex from ADS.
Closes: #175
=> gh-175: update and rename CITATION.md to CITATION.bib

.github/workflows/test.yml
It is a good practice to cancel intermediate builds (old builds when a new build on the same branch/PR starts) to save CI resources. The practice is also more environment friendly 😄 
Closes: #211
Reviewed-by: Nicolas Tessore
=> gh-211: cancel intermediate builds

.github/workflows/test.yml, .gitignore, README.md, pyproject.toml
Add code coverage in workflow using pytest-cov and coveralls.
Closes: #46
Ref: #180
=> gh-46: add infrastructure for coveralls (coverage)

CONTRIBUTING.md
The CONTRIBUTING guideline should reflect the recent change in PR title convention.
Ref: #200
=> gh-200: update CONTRIBUTING.md to follow new title convention

.github/workflows/test.yml, .gitignore, pyproject.toml
Enable doctests in CI using the pytest-doctestplus plugin.
Closes: #84
=> gh-84: enable doctests using pytest-doctestplus

.github/ISSUE_TEMPLATE/feature_request.yaml
Especially for small issues this can be a bit unnecessary so may as well remove it
=> Don't make second box mandatory for feature request

.pre-commit-config.yaml, CODE_OF_CONDUCT.md, glass/shells.py, glass/user.py
I'm not going to add it to the list of `pre-commit` hooks, as it can have a lot of false positives. But adding manually once and fixing some typos. Please remind me to remove from `pre-commit` after this PR. https://github.com/crate-ci/typos
=> Fix typos running `crate-ci/typos` over code base

.pre-commit-config.yaml, docs/examples.rst, docs/manual/releases.rst
Adds several misc `pygrep` hooks recommended by scientific python.
Refs: #170, #187
=> gh-170: add traditional pygrep hooks

.github/test-constraints.txt, .pre-commit-config.yaml
Adds several misc `pre-commit-hooks` recommended by scientific python.
Refs: #170, #187
=> gh-170: add traditional pre-commit-hooks

.github/workflows/examples.yml, .github/workflows/test.yml
Makes example tests a standalone job that executes only if something is changed in `glass/`.
Closes: #204
=> gh-204: split examples job and run it only on code changes

.github/workflows/release.yml
The developers will now be able to download wheels as artifacts from GH Actions without actually publishing a release. This helps in checking if everything is working well or if you want to distribute a pre-release wheel. Anyways, it is a good practice to keep these 2 jobs separate.
Closes: #176
Refs: #187
=> gh-176: revamp publishing workflow

.github/workflows/release.yml
The workflow now makes a PyPI upload if a release is created on GitHub, or if the workflow is triggered manually with an explicit "pypi" input. For default manual triggers, it will now upload to TestPyPI.
This might require configuring release environment in TestPyPI project.
Closes: #222
=> gh-222: add infrastructure for testpypi uploads

.github/workflows/examples.yml, .github/workflows/test.yml
Minor fix. The examples run twice on PRs right now as `branches` is not specified under `on`.
Refs: #204
=> gh-204: examples run twice on PRs

.pre-commit-config.yaml
[pre-commit's mirror of prettier](https://github.com/pre-commit/mirrors-prettier) was [archived](https://github.com/pre-commit/mirrors-prettier?tab=readme-ov-file#archived) a few months back -
> # archived
>
> prettier made some changes that breaks plugins entirely
Scientific Python recommends using https://github.com/rbubley/mirrors-prettier?tab=readme-ov-file now.
Refs: #226
=> gh-226: pre-commit's mirror of prettier is obsolete

.github/dependabot.yml, .github/workflows/examples.yml, .github/workflows/pull_request.yml, .github/workflows/release.yml, .github/workflows/test.yml, .pre-commit-config.yaml, .readthedocs.yml
Still working towards #170. The options seem like a lot but these are ones I've used and I've found great for readability. Plus, for example, removing Python versions makes diffs easier when doing something like
```yaml
python-version:
- "3.8"
- "3.9"
- "3.10"
- "3.11"
```
rather than
```yaml
python-version: ["3.8", "3.9", "3.10", "3.11"]
```
=> gh-170: add `yamllint` and run over the repo

tests/conftest.py, tests/core/test_algorithm.py, tests/test_lensing.py, tests/test_points.py
Gets rid of legacy `RandomState` and replaced it with the new random number `Generator` for rng calls.
Fixes: #208
=> gh-208: remove legacy random number generation

tests/conftest.py
Follows up https://github.com/glass-dev/glass/pull/241. See explanation of what the `scope` parameter does for `pytest.fixture`. Seems silly to not use it (although in this case the speed-up will be minimal).
=> gh-265: calculate `fixture` once per testing `session`

.github/workflows/test.yml, .pre-commit-config.yaml, pyproject.toml
Verbose output flags for both ruff and pytest are used frequently enough to be added to pyproject.toml.
Refs: #267
=> gh-267: move verbose output flag for ruff and pytest to pyproject.toml

pyproject.toml
Adds coverage config in pyproject.toml to ignore VCS produced files and conditional code meant for type checking.
Closes: #278
=> gh-278: ignore reduandant lines and files from coverage report

CONTRIBUTING.md
I have updated the contributing guideline to reflect all the recent changes. I think keeping it just on GitHub should be okay, given that the new developers will look at the GitHub repository before contributing.
Closes: #185
=> gh-185: update CONTRIBUTING.md (developer guide)

.github/workflows/examples.yml, .github/workflows/test.yml
Fixes #288. Currently a PR is never tested the moment it gets marked as draft. The idea behind not running in draft is to limit CI use, but we need to ensure everything is ran before merging to `main`.
=> gh-288: run CI when a draft PR is marked as ready

.github/ISSUE_TEMPLATE/config.yml
Closes #290. Utilise the powerful `contact_links` feature GitHub provides https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser. Tested on a dummy repo.
=> gh-290: add extra contact links to the raise issue button

README.md
Closes #293. In a previous PR, the reference text was removed, but the link was left behind. This PR removes the link.
=> gh-293: remove unused mailing list link in README

glass/core/algorithm.py, tests/core/test_algorithm.py, tests/core/test_array.py
Add missing tests for `glass.core.array.broadcast_first` and `glass.core.array.test_cumtrapz`. Improve coverage for `glass.core.algorithms.nnls`.
Closes #268
=> gh-268: add more tests for `glass.core`

glass/shapes.py, tests/test_shapes.py
Adds tests for `glass.shapes.triaxial_axis_ratio` and `glass.shapes.ellipticity_ryden04` inspired by `skypy`.
Sets up `.coveragrc` (coverage config file) to ignore unrelated files.
Closes: #276
=> gh-276: add tests for `glass.shapes`

.pre-commit-config.yaml
The PRs will not be fixed automatically, but the bot can still be triggered for fixes by commenting `pre-commit.ci autofix` on a PR.
The other functionalities (occasional version updates, running checks in the CI) will stay as it is.
=> gh-297: do not autofix PRs using pre-commit.ci

.pre-commit-config.yaml, docs/make.bat
Closes #300. Using https://github.com/Lucas-C/pre-commit-hooks pre-commit hook to make sure that no tabs creep in in future.
=> gh-300: convert tabs to spaces and disable generally

glass/core/algorithm.py, glass/fields.py, glass/galaxies.py, glass/lensing.py, glass/observations.py, glass/shapes.py, glass/shells.py, tests/core/test_array.py, tests/test_lensing.py, tests/test_points.py
Closes #246. Use `numpy.typing.NDArray` as the first step towards #280. With `NDArray` we can use types, i.e. `NDArray[np.float64]`, which I'll save for future work (#306).
I have also gone throughout and made sure anything like `ArrayLike` is using the alias `import numpy.typing as npt`. Imports are generally in a `if TYPE_CHECKING` block where possible.
We are using `numpy.testing` in some places. This was being aliased as `npt`. To avoid confusion, I have removed this alias and left them as an explicit import.
=> gh-246: replace `numpy.ndarray` with `numpy.typing.NDArray`

noxfile.py
`jupyter execute` does not work with `glob` patterns when used within `subprocess.run` or `session.run`. Now the path passed into `jupyter execute` is more explicit. Working locally (should have tested this before locally) -
```py
(.env) saransh@Saranshs-MacBook-Pro glass % nox -e examples
nox > Running session examples
nox > Re-using existing virtual environment at .nox/examples.
nox > python -m pip install -e '.[examples]'
nox > jupyter execute examples/2-advanced/stage_4_galaxies.ipynb examples/2-advanced/cosmic_shear.ipynb examples/1-basic/lensing.ipynb examples/1-basic/matter.ipynb examples/1-basic/shells.ipynb examples/1-basic/photoz.ipynb examples/1-basic/density.ipynb
[NbClientApp] Executing examples/2-advanced/stage_4_galaxies.ipynb
[NbClientApp] Executing notebook with kernel: …
```
=> gh-307: fix nox examples session

tests/core/test_array.py
The comment was right but the code was wrong 🤦🏻‍♂️
Use `np.broadcast_arrays` for comparison.
Fixes: #312
=> gh-312: fix tests for broadcast_first

tests/core/test_algorithm.py, tests/core/test_array.py, tests/test_fields.py, tests/test_fits.py, tests/test_galaxies.py, tests/test_lensing.py, tests/test_points.py, tests/test_shapes.py, tests/test_shells.py
Closes #285. Simplifies tests by just moving all imports to the top. I find this easier to read.
Have also simplified the logic to see if `scipy` is present, similarly to `fitsio`.
Also fixed the `broadcast_first` test, which was missing the `test_` prefix.
=> gh-285: move test imports to the top

.github/workflows/test.yml, .pre-commit-config.yaml
Add https://github.com/rhysd/actionlint to check through GitHub Actions workflows.
The fix was related to this error
```yaml
.github/workflows/test.yml:51:31: receiver of object dereference "key" must be type of object but got "number" [expression]
|
51 |           nox -s doctests-${{ matrix.python-version.key || matrix.python-version
|                               ^~~~~~~~~~~~~~~~~~~~~~~~~
.github/workflows/test.yml:55:31: receiver of object dereference "key" must be type of object but got "number" [expression]
|
55 |           nox -s coverage-${{ matrix.python-version.key || matrix.python-version
```
Why did we have this `matrix.python-version.key` bit @Saransh-cpp? Introduced in https://github.com/glass-dev/glass/pull/287, sorry I missed it.
=> gh-302: add `actionlint` and fix issues

pyproject.toml
Excludes `docs/`, `tests/`, `examples/`, `noxfile.py`, and all the `.*` files (except `.gitignore`) from the SDist.
Closes: #304
=> gh-304: exclude a few things from SDist

README.md
Closes #321. Makes it slightly easier to see each badge. I don't feel strongly about the sections, so we can always change them. There are probably other badges we could add, but will leave for a separate PR.
=> gh-321: group markdown badges into sections

CONTRIBUTING.md, noxfile.py, pyproject.toml
Closes #282. Run locally, the output looks like below. Makes it easy to know what needs prioritising to improve the overall score. Options come from my experience with https://github.com/astro-informatics/sleplet/blob/9d8884177135d17876a65b65dd85e99712a43622/pyproject.toml#L102-L110.
```
---------- coverage: platform darwin, python 3.12.6-final-0 ----------
Name                      Stmts   Miss Branch BrPart  Cover
-----------------------------------------------------------
glass/ext/__init__.py         6      6      2      0     0%
glass/fields.py             173    146     82      1    12%
glass/observations.py        59     47     12      0    17%
glass/shells.py             144     57     40      2    54%
glass/lensing.py            132     55     36      2    55%
glass/galaxies.py …
```
=> gh-282: extend `coverage` options to improve output

.github/workflows/test.yml
Closes #319. Reading the documentation of the action this is what you are _meant_ to do when you are using matrix builds. I've used this before.
https://github.com/coverallsapp/github-action?tab=readme-ov-file#complete-parallel-job-example
This has also fixed the `Tree` section of the `coveralls` UI which was previously just showing `core`/`ext` (and the files therein).
=> gh-319: run coverage in parallel and aggregate results

.github/workflows/test.yml, glass/fields.py, glass/lensing.py, glass/shells.py, noxfile.py, pyproject.toml, tests/test_fits.py
Closes #198. For Array API support (#67), we need minimum versions of:
1. `Python 3.9` as specified here https://data-apis.org/array-api-compat/changelog.html#id9
2. `NumPy 1.22` as specified here https://numpy.org/doc/stable/reference/array_api.html#array-api-standard-compatibility
In this PR I have enforced both of these. The code changes have come from `ruff` linting, utilising the benefits from [3.9](https://docs.python.org/3/whatsnew/3.9.html).
I also removed some of the overzealous comments on imports. They weren't adding anything and meant the imports took up more room.
=> gh-198: enforce `python>3.8` & `numpy>1.21`

.github/test-constraints.txt, noxfile.py
`Nox` will always use `virtualenv` now and the `.txt` file for constraints is in a more widely accepted format now (readable by both `uv` and plain `pip install`.
Refs: #323
=> gh-323: rm broken support for uv + update constraint format

tests/core/test_array.py, tests/test_lensing.py, tests/test_shapes.py, tests/test_shells.py
Use `numpy.testing.assert*` methods wherever possible.
Closes #327
=> gh-327: use `numpy.testing` everywhere in existing tests

glass/shapes.py
Instead of trying to reshape an array to a smaller dimension, produce an array of the same `size` and mask it.
Fixes: #328 
Fixed: `ellipticity_ryden04` does not error our with shape mismatch sporadically
=> gh-328: fix shape mismatch bug in ellipticity_ryden04

.pre-commit-config.yaml
`MNT` and `STY` keywords are not used anywhere in glass now, so it makes sense to make these automated commits and PRs have a more meaningful message.
Closes: #338
=> gh-338: better autoupdate and autofix messages for pre-commit.ci

glass/galaxies.py, tests/test_galaxies.py
I have started looking into tests for `galaxies.py` and this popped up during my research.
Closes: #137
=> gh-137: deprecate `redshifts_from_nz` in favor of `redshifts`

.github/workflows/test.yml
All of a sudden `libbz2-dev` is not present by default in GH Actions now + we were using system Python for a couple of jobs.
Closes: #342
=> gh-342: install libbz2-dev and use setup-python

tests/test_galaxies.py
Add missing tests for `glass.galaxy_shear`
Closes: #270
=> gh-270: add missing tests for glass.galaxies

docs/conf.py, glass/core/__init__.py, glass/core/algorithm.py, glass/core/array.py, glass/fields.py, glass/galaxies.py, glass/lensing.py, glass/observations.py, glass/points.py, glass/shapes.py, glass/shells.py, glass/user.py, pyproject.toml
Closes #346. Working towards #188.
The main changes here have been:
- Remove all types in the docstrings in favour of proper static typing (being added in #308)
- Switch from `numpydoc` to `sphinx.ext.napolean` due to https://github.com/numpy/numpydoc/issues/196
Have had to change the references to `[1]` rather than `[1]_` due to this bug, https://github.com/sphinx-doc/sphinx/issues/9689. Hopefully this can be fixed in the future.
Example:
`glass.lensing.from_convergence`
Raised #350, #351.
=> gh-346: enforce `NumPy` docstrings + use static typing in docs

glass/shapes.py
The code now generates only the required values while resampling making it more efficient. The implementation works with the existing test cases, but given that the function accepts `ArrayLike` args, the following fails -
```py
In [1]: from glass import ellipticity_ryden04
In [2]: mu, sigma, gamma, sigma_gamma = [-1.85, -2.85], [0.89, 0.89, 0.33], [0.056, 0.02, 0.3, 0.2], [0.222]\
In [3]: ellipticity_ryden04(mu, sigma, gamma, sigma_gamma)
----------------------------------------------------------------------
ValueError                           Traceback (most recent call last)
Cell In[3], line 1
----> 1 ellipticity_ryden04(mu, sigma, gamma, sigma_gamma)
File ~/Code/UCL/glass/glass/shapes.py:143, in ellipticity_ryden04(mu, sigma, gamma, sigma_gamma, size, rng)
141 # default size if not …
```
=> gh-328: efficient resampling in `ellipticity_ryden04`

glass/lensing.py, glass/points.py, glass/shells.py
Single backslash is for latex commands, double backslash is for newline. I don't know when or how the behavior changed, [but their latest docs still say](https://sphinx-rtd-trial.readthedocs.io/en/latest/ext/math.html#module-sphinx.ext.mathbase) -
> Keep in mind that when you put math markup in Python docstrings read by [autodoc](https://sphinx-rtd-trial.readthedocs.io/en/latest/ext/autodoc.html#module-sphinx.ext.autodoc), you either have to double all backslashes, or use Python raw strings (r"raw").
Closes: #352
=> gh-352: fix latex rendering

.pre-commit-config.yaml, docs/conf.py, glass/core/array.py, glass/ext/__init__.py, glass/fields.py, glass/galaxies.py, glass/lensing.py, glass/observations.py, glass/points.py, glass/shapes.py, glass/shells.py, glass/user.py, pyproject.toml, tests/conftest.py, tests/core/test_algorithm.py, tests/core/test_array.py, tests/test_fields.py, tests/test_fits.py, tests/test_galaxies.py, tests/test_lensing.py, tests/test_points.py, tests/test_shapes.py, tests/test_shells.py
Adding `mypy` to a pre-existing codebase is never easy. I initially attempted this in #308, but have since split this up into separate issues:
In this PR, `mypy` is added but in order for CI to pass, the `# type: ignore[]` syntax is used throughout. I didn't want to tackle these here too (see #308) as it gets quite messy.
One thing I have done (following #356) is change every empty `npt.NDArray` to `npt.NDArray[typing.Any]` (see #330), as this actually results in fewer errors than leaving them all blank. Ideally, we'd like to fill in as many of the `typing.Any` as possible - they're a bit useless by themselves. However, that is not the priority for now. Plus, I expect typing to change when #67 is tackled.
=> gh-280: add `mypy` to codebase

tests/test_galaxies.py, tests/test_shapes.py
The coverage went down when branch coverage was turned on. This PR brings it back to 100% for these two files.
Refs: #161
=> gh-161: bump coverage for galaxies and shapes

glass/observations.py, glass/points.py, glass/shapes.py
I think due to development velocity, I accidentally brought these back in when addressing merge conflicts
=> Fix `Returns` in docstrings (I think entered in #357)

.github/workflows/test.yml
None of the available Ubuntu images - [Ubuntu 20.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2004-Readme.md#installed-apt-packages), [Ubuntu 22.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#installed-apt-packages), and [Ubuntu 24.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#installed-apt-packages) - list it as an installed `apt` package so I am not sure how or when this was fixed.
Refs: #342
=> gh-342: explicit libbz2-dev installation is not required now

glass/__init__.py, glass/galaxies.py
Closes #399. Hides the `kappa_ia_nla` function introduced in #21. This appeared to depend on functionality in https://github.com/glass-dev/cosmology that has not made it into the latest (now deprecated) release. It has been discussed that we should keep it but don't make it publicly available. Needed for #390.
=> gh-399: hide `kappa_ia_nla`

.github/workflows/release.yml, CITATION.cff, CONTRIBUTING.md, README.md, docs/manual/first-steps.rst, pyproject.toml
Closes #286. Upon building the `sdist` we can replace `stable` with the relevant tag.
Have also used `stable` as the default throughout. This wasn't possible when issue #286 was created, as the `stable` tag didn't exist.
=> gh-286: replace `stable` in docs with tag for `sdist`

glass/fields.py, glass/points.py, glass/user.py
Closes #418. Without these names, they render as "special-cased".
=> gh-418: add variable names for `Yields` vars

CHANGELOG.md, CONTRIBUTING.md, docs/manual/releases.rst
This is the release PR for v2024.2.
Closes: #390
=> gh-390: release 2024.2

.github/workflows/release.yml
This should fix the release action. The git tag is stored into the environment after the README.md is made dirty, where setuptools-scm picks it up as the current version.
Closes: #430
=> gh-430: fix for release action

glass/observations.py
Closes #443. In theory one should be able to use `nbins` or `dz`, but the current implementation actually forbids `nbins`.
=> gh-443: `if` should be `elif` in `fixed_zbins`

glass/observations.py
Closes #447. Discovered in #436.
> Values are generated within the half-open interval [start, stop)
Due to the use of `np.arange` one needs to add the step to `zmax` in the function call.
=> gh-447: make sure `dz` gives the same results as `nbins`

tests/conftest.py, tests/test_lensing.py
This makes them available to all tests. I need `cosmo` for use in #449.
Have also added `scope="session"` so they are only computed once when testing rather than multiple times.
=> gh-450: move all `pytest.fixture` into `conftest.py`

.github/workflows/pull_request.yml
Dependabot PRs will now be ignore in the workflow.
Fixes: #453
=> gh-453: don't run PR title checker on dependabot PRs

tests/test_fields.py
Add tests and bump coverage to ~100 for `glass.fields`.
Closes: #269
=> gh-269: add tests for glass.fields

.github/workflows/release.yml
Closes #421. Allows one to use `workflow_dispatch` to deploy the current setup to TestPyPI, this should allow us to test things work as expected.
However, it still ensures that the `publish` workflow is still protected by the GitHub environment. This is achieved by changing the name of the job to `test-publish` when called with called by `workflow_dispatch`.
=> gh-421: fix TestPyPI deployment

noxfile.py
`nox -s examples` now updates the notebooks inplace.
Closes: #460
=> gh-460: update notebooks inplace when running nox -s examples

.github/test-constraints.txt, pyproject.toml, tests/core/test_algorithm.py, tests/core/test_array.py
Remove scipy as a test dependency and replace the tests with scipy's internal tests.
Closes: #440
=> gh-440: remove scipy as a test dependency

.github/workflows/pull_request.yml
Fixes #469. In https://github.com/glass-dev/glass/pull/467 the title workflow was successfully skipped, but then I made a change and it failed. The check should be changed for the PR author instead using `github.event.pull_request.user.login`.
=> gh-469: @pre-commit.ci shouldn't break title checking

.github/workflows/release.yml
Use `hynek/build-and-inspect-python-package@v2` as recommended by Scientific Python.
Closes: #464
=> gh-464: simplify release infrastructure

git_archival.txt, gitattributes.txt
This is required if glass is installed through the files in GitHub releases.
Closes: #465
=> gh-465: enable installing glass through git archives

.github/workflows/test.yml, CONTRIBUTING.md, noxfile.py, tests/conftest.py
Inspired heavily from SciPy's infrastructure, this PR adds a way to test array API compatibility (more specifically, `array_api_strict` and `jax`, which can be easily scaled to other libraries in the future).
SciPy does in fact test its functions on every supported array library, instead of just relying on `array_api_strict`. `array_api_strict` will test the shared functionality, but will fail to identify functionalities which are not standardized and where libraries deviate from each other (such as immutability in `jax`); hence, testing with every library sounds like a good idea.
Closes: #439
=> gh-439: infrastructure for testing array API compatibility

.github/PULL_REQUEST_TEMPLATE.md
Adds a PR template to make the CHANGELOG compiling process easier.
Closes: #424
=> gh-424: add a simple PR template

tests/test_lensing.py, tests/test_observations.py, tests/test_points.py
Closes #275. Adds tests for the `glass.shells` module. Coverage going up - 88.9%.
Worked on this before the pause. Can't remember where I got to, but makes sense to merge. We can always improve the tests later.
=> gh-275: add tests for `glass.lensing`

.pre-commit-config.yaml, glass/core/array.py, glass/lensing.py, glass/observations.py, glass/points.py, glass/shells.py
Fixes most of the errors. See my comments below for a better explanation.
Refs: #480
=> gh-480: fix mypy failures

.github/workflows/examples.yml, .github/workflows/test.yml
- The nox environment should be cached after setup-python cache (as setup-python exposes env.pythonLocation which is used in nox cache)
- noxfile's hash should be used in the key while caching nox environments
- env.pythonLocation should be used in the cache key to not confuse the runners between system-wide and environment-specific python
Closes: #506
=> gh-506: cache dependencies correctly

glass/core/__init__.py, glass/fields.py, glass/galaxies.py, glass/grf/_core.py, glass/grf/_transformations.py, glass/lensing.py, glass/observations.py, glass/points.py, glass/shapes.py, glass/shells.py, glass/user.py, pyproject.toml
Removes D205, D401, EM101, EM102, TRY003, as agreed in the issue discussion.
Closes: #499
=> gh-499: rm D205, D401, EM101, EM102, TRY003

glass/__init__.py
Use a `try-except` block instead of `contextlib.suppress` so that the `glass` namespace is not polluted.
Also, the error we should be looking for is `ModuleNotFoundError` and not `PackageNotFoundError`.
Closes: #491
=> gh-491: use try-except for __version__

docs/user/how-glass-works.rst, glass/fields.py, glass/galaxies.py, glass/grf/_solver.py, glass/grf/_transformations.py, glass/lensing.py, glass/observations.py, glass/points.py, glass/shells.py, pyproject.toml, tests/conftest.py, tests/core/test_algorithm.py, tests/core/test_array.py, tests/grf/test_core.py, tests/test_fields.py, tests/test_galaxies.py, tests/test_lensing.py, tests/test_observations.py, tests/test_points.py, tests/test_shapes.py, tests/test_shells.py, tests/test_user.py
Changes the code throughout to use `import glass` rather than `from glass import` where possible. This is possible via the `__all__` statements in `__init__.py`. I have also done this for `glass.grf`.
Closes: #501
=> gh-501: change imports to be directly from `glass`

.pre-commit-config.yaml, glass/shells.py
NumPy 2.2.3 fixes the return signature of `union1d`. See https://github.com/numpy/numpy/issues/28239 for more discussion.
Closes: #480
=> gh-480: fix union1d typing error

glass/fields.py
My bad. #523 introduced some occurrences of `inv_triangle_number` which went unnoticed. Prime example of why you should make your PRs "up-to-date" before merging.
Refs: #509
=> gh-509: new inv_triangle_number popped up in another PR

glass/fields.py
Update the type annotation of `glass_to_healpix_spectra()` and `healpix_to_glass_spectra()` to reflect they work with arbitrary sequences.
Closes: #530
Changed: more permissive type hints for `glass_to_healpix_spectra()` and `healpix_to_glass_spectra()`
=> gh-530: more permissive typing of GLASS/HEALPix order functions

.all-contributorsrc.json, README.md
This adds https://github.com/all-contributors/all-contributors as a way to add contributors to the README. As per request, I have taken inspiration from this discussion https://github.com/all-contributors/all-contributors/issues/85 for a minimal configuration. Specifically, this repository has an example that I think satisfies the requirement https://github.com/jdalrymple/gitbeaker. In particular, [these template lines](https://github.com/jdalrymple/gitbeaker/blob/cccf261448125d94ce26258ed7e5599a35463733/.all-contributorsrc#L15-L17). This will take a bit of experimenting.
@ntessore as per the docs https://allcontributors.org/docs/en/bot/installation can you install the app https://github.com/apps/allcontributors/installations/select_target for this repository?
I think to then add people …
=> gh-540: add all contributors config

.github/PULL_REQUEST_TEMPLATE.md
Hides the CHANGELOG entry by default.
Fixes: #547
=> gh-547: comment out CHANGELOG entry by default

examples/2-advanced/legacy-mode.ipynb
The `labels` argument was initially set to `[]` which is bad practice https://docs.astral.sh/ruff/rules/mutable-argument-default. This should be set to `None` and then within the function should be set to the initial empty list.
Fixes: #578
Fixed: A mutable argument bug in the legacy mode notebook
=> gh-578: mutable argument should be empty list rather than `None`

.github/workflows/examples.yml
The examples roughly take 12-13 minutes to run. A 20 minutes timeout on this particular step should be good!
Closes: #571
=> gh-571: add a 20 min timeout to example runs

.github/workflows/examples.yml
At the moment, the example notebooks do not run in the CI if files in the `examples/` directory are modified.
Closes: #580
=> gh-580: examples should run in the CI if they are modified

glass/__init__.py, glass/shells.py, tests/test_shells.py
The weight functions (`distance_weight`/`volume_weight`/`density_weight`) have been changed to callable classes (`DistanceWeight`/`VolumeWeight`/`DensityWeight`). The logic here being that the weight functions will now have compatible typing signatures to `tophat_windows`/`linear_windows`/`cubic_windows`, which expect `Callable[[ArrayLike1D], NDArray[np.float64]] | None`.
Closes: #568
Changed: The weight functions have been changed to callable classes
=> gh-568: convert `_weight` funcs to classes for `_windows` funcs

noxfile.py
Add `--doctest-plus-generate-diff=overwrite` to the `doctests` Nox session so that the outputs are fixed on the fly.
Closes: #592
=> gh-592: use `--doctest-plus-generate-diff=overwrite`

.pre-commit-config.yaml, glass/fields.py
I finally got it. The mypy error Python 3.13, but pre-commit.ci is for some reason not using Python 3.13.
I finally get the error on CI here - https://results.pre-commit.ci/run/github/357271805/1744297435.iNZbr3uAQbKHw8dma-TZww
This PR pins the Python version and adds a soft pin to the NumPy version (recommended).
Closes: #602
=> gh-602: pin python version and numpy for pre-commit

glass/algorithm.py, glass/arraytools.py, tests/test_arraytools.py
We will be using `xp` etc. throughout the Array API conversion. Currently, changes in this PR have been put in PRs such as #597, but it would make sense that we make these changes separately so downstream PRs only reflect actual Array API changes.
Closes: #599
=> gh-599: swap all `xp` vars to `xq` (and similar)

CONTRIBUTING.md, tests/conftest.py
Remove `@array_api_compatible` decorator and introduce `xp` fixture.
Closes: #611
=> gh-611: xp fixture for array API tests

glass/algorithm.py, tests/test_algorithm.py
Add array API tests for legacy mode functions added in `glass.algorithm`. The functions added in other modules do not fully support the array API standard; therefore, those functions can be dealt with once we add full support.
Closes: #519
=> gh-519: test array API compliance of legacy mode functions

.github/workflows/release.yml
PyPI and TestPyPI deployments should be separate now.
Closes: #594
=> gh-594: split PyPI and TestPyPI deployments

pyproject.toml
A recent change (see #629) is causing the tests to fail. Following this suggestion idea https://github.com/data-apis/array-api-extra/pull/343#issuecomment-3020606203 and not wanting to drop `Python<3.12` this is a compromise.
=> gh-629: temporarily pin `array-api-strict`

glass/fields.py, tests/test_fields.py
Fix bug where `compute_gaussian_spectra()` did not skip over empty spectra.
Fixes: #639
=> gh-639: fix compute_gaussian_spectra() for empty spectra
